#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

squid_port=$YNH_APP_ARG_SQUID_PORT

app=$YNH_APP_INSTANCE_NAME

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression --message="Configuring firewall..."

# Find an available port
squid_port=$(ynh_find_port --port=$squid_port)
ynh_app_setting_set --app=$app --key=squid_port --value=$squid_port

# Open the port
ynh_script_progression --message="Configuring firewall..."
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $squid_port

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..."

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..."

# See if squid3 folder exits
if [ -d "/etc/squid3" ]; then
	squid="squid3"

# If squid3 folder is not found look for squid folder
elif [ -d "/etc/squid" ]; then
	squid="squid"

# If both folders are not found then call ynh_die
else
	ynh_die --message="No squid folder found in /etc. Looks like squid3 package is not installed. Try installing it manually."

fi
ynh_app_setting_set --app=$app --key=squid_folder --value=$squid

ynh_add_config --template="../conf/squid.conf" --destination="/etc/$squid/squid.conf"

#=================================================
# GENERIC FINALIZATION
#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service add $squid --description "Squid3 a web proxy service" --log="/var/log/$squid/access.log" --needs_exposed_ports $squid_port

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

# Start a systemd service
ynh_systemd_action --service_name=$squid --action="restart" --log_path="/var/log/$squid/cache.log"

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

echo "You can find a config file at /etc/$squid/squid.conf
Squid 3 will work with your registered users through LDAP. Just put the username and password when asked.

To configure on Firefox go to preferences->general->network proxy->manual proxy configuration.

Enter these value in the below feilds.
---------------------------------------------------------------------
| Http proxy: Your any registered domain name or ip eg domain.tld
|
|port: $squid_port
|
|Tick mark use this proxy server for all protocols
|
|No proxy for: localhost, 127.0.0.1
|
|Save and restart borwser.
---------------------------------------------------------------------
If you are facing any issues or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/squid3_ynh/issues" > mail_to_send

ynh_send_readme_to_admin --app_message="mail_to_send" --type="install"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
