#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	#### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

port=$(ynh_app_setting_get $app port)

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies squid3

#=================================================
# SPECIFIC RESTORE
#=================================================
# OPEN PORTS
#=================================================

yunohost firewall allow --no-upnp TCP $port

#=================================================
# RESTORE INOTIFY'S CONFIG
#=================================================
ynh_secure_remove "/etc/squid3/squid.conf"	
ynh_restore_file  "/etc/squid3/squid.conf"
service squid3 restart
#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add squid3  --log "/var/log/squid/access.log"


#=================================================
# SEND A README FOR THE ADMIN
#=================================================

message="You can find a config file at /etc/squid3/squid.conf
Squid 3 will work with your registered users. Just put the username and password when asked.

To configure on Firefox go to preferences->general->network proxy->manual proxy configuration.

Enter these value in the below feilds.

Http proxy: your any registered domain name or ip

port: $port

Tick mark use this proxy server for all protocols

No proxy for: localhost, 127.0.0.1

Save and restart borwser.

If you facing an issue or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/squid3_ynh/issues"

ynh_send_readme_to_admin --app_message="$message" --recipients="root"


