#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME
squid_port=$(ynh_app_setting_get $app squid_port)
new_port=$(ynh_app_setting_get $app new_port)

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
ynh_script_progression --message="Backing up the app before upgrading (may take a while)..."

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors


#=================================================
# SPECIFIC RESTORATION
#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression --message="Upgrading dependencies..."

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# CLOSE A PORT
#=================================================
# If #new_port is not defined test the $port and keep it open
if [ -z $new_port ]; then
	ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $squid_port
	ynh_app_setting_set --app=$app --key=port --value=$squid_port
	# If $new_port is define close the $port and open the $new_port
else
	#Close $port
	if yunohost firewall list | grep -q "\- $squid_port$"
	then
		ynh_script_progression --message="Closing port $squid_port..."
		ynh_exec_warn_less yunohost firewall disallow TCP $squid_port
	fi

	# Open $new_port
	port=$(ynh_find_port --port=$squid_new_port)
	#Add the value of $new_port to $port
	ynh_app_setting_set --app=$app --key=squid_port --value=$squid_port
	#Remove the value of $new_port
	ynh_app_setting_set --app=$app --key=new_port --value=""
fi


#=================================================
# MODIFY A CONFIG FILE
#=================================================

### `ynh_replace_string` is used to replace a string in a file.
### (It's compatible with sed regular expressions syntax)

# See is squid3 folder is there
if [ -d "/etc/squid3" ]; then
		squid="squid3"

# If squid3 folder is not found look for squid folder
elif [ -d "/etc/squid" ]; then
		squid="squid"

# If both folders are not found then call ynh_die
else
		ynh_die "No squid folder found in /etc. Looks like squid 3 package is not installed. Try installing it manually by apt-get install squid3"

fi
### Verify the checksum of a file, stored by `ynh_store_file_checksum` in the install script.
### And create a backup of this file if the checksum is different. So the file will be backed up if the admin had modified it.
ynh_backup_if_checksum_is_different --file="/etc/$squid/squid.conf"

ynh_replace_string --match_string="__PORT__"    --replace_string="$squid_port"   --target_file="../conf/squid.conf"
ynh_replace_string --match_string="__SQUID__"   --replace_string="$squid"   --target_file="../conf/squid.conf"
cp -f "../conf/squid.conf" "/etc/$squid/."
# Save squid folder
ynh_app_setting_set --app=$app --key=squid_folder --value=$squid



# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum --file="/etc/$squid/squid.conf"

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

### `yunohost service add` is a CLI yunohost command to add a service in the admin panel.
### You'll find the service in the 'services' section of YunoHost admin panel.
### This CLI command would be useless if the app does not have any services (systemd or sysvinit)
### If you're not using these lines:
###		- You can remove these files in conf/.
###		- Remove the section "REMOVE SERVICE FROM ADMIN PANEL" in the remove script
###		- As well as the section ADVERTISE SERVICE IN ADMIN PANEL" in the restore script

yunohost service add squid3 --log "/var/log/$squid/cache.log"

#=================================================
# RESTART SQUID'S SERVICE and SSOWATCONF
#=================================================

service $squid restart
yunohost app ssowatconf

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

echo "You can find a config file at /etc/$squid/squid.conf
Squid 3 will work with your registered users through LDAP. Just put the username and password when asked.

To configure on Firefox go to preferences->general->network proxy->manual proxy configuration.

Enter these value in the below feilds.
---------------------------------------------------------------------
| Http proxy: Your any registered domain name or ip eg domain.tld
|
|port: $squid_port
|
|Tick mark use this proxy server for all protocols
|
|No proxy for: localhost, 127.0.0.1
|
|Save and restart borwser.
---------------------------------------------------------------------
If you are facing any issues or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/squid3_ynh/issues" > mail_to_send

ynh_send_readme_to_admin --app_message="mail_to_send" --type="install"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed"
